### ISSUE TITLE
Visual Studio 2017 Update 3 / MSBuild 15.3

### ISSUE THREAD

**Issue by uli-weltersbach** [3F/hMSBuild#3]
Microsoft decided to put v15.3 of MSBuild.exe in `<VS2017 install dir>\MSBuild\15.0\Bin`, not `<VS2017 install dir>\MSBuild\15.3\Bin`.

![MSBuild.exe version](https://user-images.githubusercontent.com/1416006/29354289-5bc37f38-826d-11e7-99d5-d22b1ab461fa.png)

This means that the `vsver` variable is set incorrectly after updating to Visual Studio 2017 Update 3.
We've fixed it locally by changing line 323 of hMSBuild.bat (v1.2.1) from `set vsver=%%a.%%b` to `set vsver=%%a.0`.

Thanks for making your script available to the public, by the way :)

**Comment by 3F** [comment]
thanks for the report

well, the main question what the directory name was planned by our MS for this at all -_-

because it extracted as {major}.{minor} version from installedVersion at this command `-latest -requires Microsoft.Component.MSBuild`

* installationVersion: 15.0.26430.12 -> ... \MSBuild\15.0\Bin
* installationVersion: 15.3.26730.3  -> yes, still ... \MSBuild\15.0\Bin

seems it probably can be like with .net framework and `v4.0.30319` folder

Does anyone may clarify information about this ? Are you sure about `{major}.0` ?

> Thanks for making your script available to the public, by the way :)

I'm glad that it also helps for someone else ^_^

**Comment by rainersigwald** [comment]
> Does anyone may clarify information about this ? Are you sure about `{major}.0` ?

The version in the directory structure is the [`ToolsVersion`](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion), not the Visual Studio version number. Historically, ToolsVersion has been fixed for a major version of Visual Studio. We don't have plans to change that at the moment, so `{major.0}` should work for the foreseeable future.

**Comment by 3F** [comment]
@rainersigwald 

I see, thanks for the detailed information !
